### ISSUE TITLE
Could you provide drivers that support OpenWRT-19.07.10? Running on MT7628. Thank you very much!

### ISSUE THREAD

**Issue by l1uhong** [XinRoom/Openwrt_rtl8811cu#1]
I tried to run OpenWRT-19.07.10 on MT7628, but I had a lot of problems compiling RTL8811CU. Could you provide drivers that support OpenWRT-19.07.10? Running on MT7628. Thank you very much!

**Comment by XinRoom** [comment]
有报错日志吗？
可以使用`make -j1 V=s`看看编译的时候有什么报错

**Comment by ghost** [comment]
![image](https://user-images.githubusercontent.com/46449647/175454279-06294765-ca3f-461c-8802-68365531d18a.png)
编译通过了，开机后dmesg打印的日志

**Comment by XinRoom** [comment]
查了下，是架构不同导致的，编译前需要在对应的驱动源码路径下执行更改架构指令：

我看了下Makefile https://github.com/morrownr/8821cu-20210118/blob/main/Makefile ，和mipsel架构相关的有：
CONFIG_PLATFORM_RTK_DMP、
CONFIG_PLATFORM_ACTIONS_ATV5201
你可以分别试一试。

```
sed -i 's/CONFIG_PLATFORM_I386_PC = y/CONFIG_PLATFORM_I386_PC = n/g' Makefile
sed -i 's/CONFIG_PLATFORM_RTK_DMP = n/CONFIG_PLATFORM_RTK_DMP = y/g' Makefile
```

```
sed -i 's/CONFIG_PLATFORM_I386_PC = y/CONFIG_PLATFORM_I386_PC = n/g' Makefile
sed -i 's/CONFIG_PLATFORM_RTK_DMP = y/CONFIG_PLATFORM_RTK_DMP = n/g' Makefile
sed -i 's/CONFIG_PLATFORM_ACTIONS_ATV5201 = n/CONFIG_PLATFORM_ACTIONS_ATV5201 = y/g' Makefile
```

**Comment by ghost** [comment]
好的，感谢，我试试

**Comment by ghost** [comment]
###################### Platform Related #######################
CONFIG_PLATFORM_I386_PC = n
CONFIG_PLATFORM_ARM_RPI = n
CONFIG_PLATFORM_ARM64_RPI = n
CONFIG_PLATFORM_ANDROID_X86 = n
CONFIG_PLATFORM_ANDROID_INTEL_X86 = n
CONFIG_PLATFORM_JB_X86 = n
CONFIG_PLATFORM_ARM_S3C2K4 = n
CONFIG_PLATFORM_ARM_PXA2XX = n
CONFIG_PLATFORM_ARM_S3C6K4 = n
CONFIG_PLATFORM_MIPS_RMI = n
CONFIG_PLATFORM_RTD2880B = n
CONFIG_PLATFORM_MIPS_AR9132 = n
CONFIG_PLATFORM_MIPS_MT7628 = y
CONFIG_PLATFORM_RTK_DMP = n
CONFIG_PLATFORM_MIPS_PLM = n
CONFIG_PLATFORM_MSTAR389 = n
...

ifeq ($(CONFIG_PLATFORM_MIPS_MT7628), y)
EXTRA_CFLAGS += -DCONFIG_LITTLE_ENDIAN
EXTRA_CFLAGS += -DCONFIG_IOCTL_CFG80211 -DRTW_USE_CFG80211_STA_EVENT
ARCH := mips
#CROSS_COMPILE = mipsel-openwrt-linux-musl-
CROSS_COMPILE ?=
KSRC := $(TOPDIR)/build_dir/target-mipsel_24kc_musl/linux-ramips_mt76x8/linux-5.4.188
endif

在Makefile中新增一个案例，然后就可以了

**Comment by XinRoom** [comment]
棒！
