### ISSUE TITLE
师傅是否可以帮忙看看树莓派3B+ 如何编译的？报错如下

### ISSUE THREAD

**Issue by ka635574222** [XinRoom/Openwrt_rtl8811cu#2]
<img width="909" alt="WX20220630-120427@2x" src="https://user-images.githubusercontent.com/22819544/176590381-246947ed-bf1e-4188-823c-3f1d2bb465ef.png">

**Comment by ka635574222** [comment]
解决了～～

**Comment by XinRoom** [comment]
咦，咋解决的，是因为你用的驱动代码不同，导致驱动补丁打不上去吗？然后你手动patch了下？留个记录可以给后来者参考。
