### ISSUE TITLE
how to install a package

### ISSUE THREAD

**Issue by n5320** [XinRoom/Openwrt_rtl8811cu#6]
how to install a package kmod-rtl8821cu?
When will it appear in official openwrt packages?

**Comment by XinRoom** [comment]
You need to compile the driver when you compile the openwrt system. Or use the sdk corresponding to the kernel version https://openwrt.org/docs/guide-developer/toolchain/using_the_sdk
It shouldn't be in the official library.
See https://openwrt.org/docs/guide-developer/helloworld/chapter4
